// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAbsensi.Repositories;

#nullable disable

namespace TestAbsensi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240724141106_Initial4")]
    partial class Initial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestAbsensi.Models.AbsensiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateIn")
                        .HasColumnType("date");

                    b.Property<int>("KaryawanId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("TimeIn")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("TimeOut")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("KaryawanId");

                    b.ToTable("t_absensi");
                });

            modelBuilder.Entity("TestAbsensi.Models.KaryawanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("m_karyawan");
                });

            modelBuilder.Entity("TestAbsensi.Models.AbsensiModel", b =>
                {
                    b.HasOne("TestAbsensi.Models.KaryawanModel", "Karyawan")
                        .WithMany()
                        .HasForeignKey("KaryawanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Karyawan");
                });
#pragma warning restore 612, 618
        }
    }
}
